const ProductosFuentes = [
    {
      id: 10,
      nombre: 'cocodrilo',
      rating: 2,
      precio: 5000,
      descripcion: 'vereda cocodrilo es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
      descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
      imagen: 'cocodrilo', // solo el nombre de la imagen sin la extensión
    },
    {
        id: 2,
        nombre: 'balin',
        rating: 2,
        precio: 3000,
        descripcion: 'vereda balin es ideal para superfices con mucho transito en subida como cocheras, patios, galerias y frentes',
        descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
        imagen: 'balin',
    },
    {
        id: 3,
        nombre: 'Tres panes',
        rating: 5,
        precio: 4000,
        descripcion: 'vereda tres panes es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
        descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
        imagen: 'trespanes',
    },
    {
        id: 4,
        nombre: 'florcita',
        rating: 5,
        precio: 3500,
        descripcion: 'vereda florcita por si dibujpo artistico es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
        descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
        imagen: 'florcita',
    },
    {
      id: 5,
      nombre: 'loseta de granito',
      rating: 5,
      precio: 3500,
      descripcion: 'vereda de granito  por si dibujpo artistico es ideal para interiores con mucho transito como cocheras, patios, galerias y frentes',
      descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
      imagen: 'losetaGranito',
  },
  {
    id: 6,
    nombre: 'Florcita',
    rating: 5,
    precio: 3500,
    descripcion: 'vereda florcita por si dibujpo artistico es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
    descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
    imagen: 'florcita',
},
{
  id: 7,
  nombre: 'Cuatro Panes',
  rating: 6,
  precio: 3000,
  descripcion: 'vereda florcita por si dibujpo artistico es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
  descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
  imagen: 'cuatroPanes',
},
{
  id: 8,
  nombre: 'mallaHexa',
  rating: 5,
  precio: 3500,
  descripcion: 'vereda florcita por si dibujpo artistico es ideal para superfices con mucho transito como cocheras, patios, galerias y frentes',
  descripcionExpandida: 'se puede lavar con cualquier liquido , solo evitar los erosivos',
  imagen: 'mallaHexa',
},
  ];

export default ProductosFuentes;